name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: list dir
        run: ls
      - name: Task 2
        run: echo "This is task 2"
      - name: Task 3
        run: echo "This is Task 3"
